name: maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  it-test:
    name: Build and test
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --errors --batch-mode
